/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/v1/login": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Exchange credentials for a JWT */
        post: operations["login"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/logout": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Revoke the bearer token (server-side denylist) */
        post: operations["logout"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/users": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List users
         * @description Any authenticated user may list. Supports offset pagination, sorting and filtering.
         *
         *     - Sortable fields: `id`, `name`, `email`, `role`. Default sort is `id` ascending.
         *       `id` ascending is always appended as a deterministic tiebreaker.
         *     - Filters (all optional, all whitelisted):
         *       - `name` — case-insensitive substring match against `name`.
         *       - `email` — case-insensitive substring match against `email`.
         *       - `role` — exact match, `ADMIN` or `USER`.
         *       - `teamId` — restrict to users who are members of the given team.
         *
         *     Malformed query parameters (unknown sort field, unknown role, out-of-range page/pageSize)
         *     respond with `400` and a `ProblemDetail` body.
         */
        get: operations["listUsers"];
        put?: never;
        /**
         * Create a user
         * @description Requires ADMIN. If the request body omits `role`, the new user defaults to `USER`.
         */
        post: operations["createUser"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/users/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: components["parameters"]["ResourceId"];
            };
            cookie?: never;
        };
        /**
         * Fetch a user by id
         * @description Requires the caller to be the target user, or to be ADMIN.
         */
        get: operations["getUser"];
        put?: never;
        post?: never;
        /**
         * Delete a user
         * @description Requires ADMIN.
         */
        delete: operations["deleteUser"];
        options?: never;
        head?: never;
        /**
         * Update a user (partial)
         * @description Partially updates a user's `name`, `email`, and `role`. This is a `PATCH`: the password
         *     cannot be changed here (the existing password is preserved) and an omitted `role` keeps the
         *     user's current role. Requires the caller to be the target user, or to be ADMIN.
         *     Only ADMIN may change a user's `role`; a non-ADMIN caller must either
         *     omit `role` or send the value the user already has, otherwise the request is rejected with 403.
         */
        patch: operations["patchUser"];
        trace?: never;
    };
    "/api/v1/users/{id}/password": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: components["parameters"]["ResourceId"];
            };
            cookie?: never;
        };
        get?: never;
        /**
         * Change a user's password
         * @description Sets a new password for the user. Only the password is changed; no other
         *     fields are touched. Requires the caller to be the target user, or to be ADMIN.
         */
        put: operations["changeUserPassword"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/teams": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List teams
         * @description Any authenticated user may list. Supports offset pagination, sorting, and filtering.
         *
         *     - Sortable fields: `id`, `name`. Default sort is `id` ascending; `id` ascending
         *       is always appended as a deterministic tiebreaker.
         *     - Filters (all optional):
         *       - `name` — case-insensitive substring match against the team's name.
         *       - `managerId` — exact match against the team's manager id.
         *       - `memberId` — restrict to teams the given user is a member of.
         *
         *     Each returned item includes the manager's `name` resolved via join so the UI
         *     does not need an N+1 lookup.
         *
         *     Malformed query parameters (unknown sort field, non-numeric managerId,
         *     out-of-range page/pageSize) respond with `400` and a `ProblemDetail` body.
         */
        get: operations["listTeams"];
        put?: never;
        /**
         * Create a team
         * @description Any authenticated user may create a team, but the `managerId` in
         *     the request body must equal the caller's own user id (ADMIN may
         *     designate any user).
         */
        post: operations["createTeam"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/teams/members": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List members of the caller's teams
         * @description Lists team members scoped by `view`. Scoping is always relative to the caller,
         *     including ADMIN callers.
         *
         *     - `view=member` (the default): members of teams where the caller is a member.
         *       The caller's own rows are excluded. Team managers never appear — a manager is
         *       not a `team_members` row.
         *     - `view=managed`: members of teams where the caller is the manager.
         *     - `view=managers`: the managers of teams where the caller is a member. Each item
         *       describes a manager (in `userId`/`name`/`email`) and the managed team. The
         *       caller is excluded.
         *
         *     Each item is one (user, team) pair — a user who shares several teams with the
         *     caller appears once per team. Soft-deleted users and soft-deleted teams are
         *     excluded.
         *
         *     Supports offset pagination, sorting and filtering.
         *
         *     - Sortable fields: `id` (the member's user id), `name`, `email`, `teamName`.
         *       Default sort is `id` ascending. `id` ascending and the team id ascending are
         *       always appended as deterministic tiebreakers.
         *     - Filters (all optional, all whitelisted):
         *       - `name` — case-insensitive substring match against the member's name.
         *       - `email` — case-insensitive substring match against the member's email.
         *       - `teamId` — exact match against the team's id.
         *
         *     Malformed query parameters (unknown view, unknown sort field, non-numeric
         *     teamId, out-of-range page/pageSize) respond with `400` and a `ProblemDetail` body.
         */
        get: operations["listTeamMembers"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/teams/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: components["parameters"]["ResourceId"];
            };
            cookie?: never;
        };
        /**
         * Fetch a team
         * @description Any authenticated user may read.
         */
        get: operations["getTeam"];
        /**
         * Replace a team
         * @description Requires the caller to be the team's current manager, or to be ADMIN.
         */
        put: operations["replaceTeam"];
        post?: never;
        /**
         * Delete a team
         * @description Requires the caller to be the team's current manager, or to be ADMIN.
         */
        delete: operations["deleteTeam"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/teams/{id}/members/{userId}": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: components["parameters"]["ResourceId"];
                userId: components["parameters"]["UserIdInPath"];
            };
            cookie?: never;
        };
        get?: never;
        /**
         * Add a member to the team (idempotent)
         * @description Requires the caller to be the team's current manager, or to be ADMIN.
         */
        put: operations["addTeamMember"];
        post?: never;
        /**
         * Remove a member from the team
         * @description Requires the caller to be the team's current manager, or to be ADMIN.
         */
        delete: operations["removeTeamMember"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/feedbacks": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List feedbacks for the caller
         * @description Lists feedback records scoped by `view`. Scoping is always relative to the caller,
         *     including ADMIN callers.
         *
         *     - `view=received` (the default): rows where the caller is the **subject** AND one of:
         *       (a) the row has no requester and `status` is `SENT`/`WITHDRAWN`; (b) the caller is the
         *       requester (any status/visibility); or (c) someone else is the requester, `visibility`
         *       is `PROVIDER_SUBJECT`/`PROVIDER_REQUESTER_SUBJECT`/`PUBLIC`, and `status` is
         *       `SENT`/`WITHDRAWN`. `PROVIDER_REQUESTER` rows appear only via (b). A `DRAFT`/`REQUESTED`
         *       row the caller requested has its `contentPreview` redacted (empty) until it is sent.
         *     - `view=provided`: rows where the caller is the provider, regardless of visibility
         *       (a provider may always read their own records).
         *     - `view=team`: rows where the subject is a member of a non-deleted team the caller manages
         *       (the caller's subordinates), AND the caller is a **party** to the row — its provider or
         *       requester (at any status) — OR `status` is `SENT`/`WITHDRAWN`. Intended for a manager's
         *       overview; in-progress (`DRAFT`/`REQUESTED`/`REJECTED`) rows the manager is not a party to
         *       are excluded. A caller who manages no team gets an empty page. When the manager is also
         *       the requester of an unfinished row, its `contentPreview` is redacted (empty) until sent.
         *
         *     Supports offset pagination, sorting and filtering.
         *
         *     - Sortable fields: `id`, `requesterName`, `subjectName`, `providerName`, `visibility`,
         *       `status`, `lastModified`. Default sort is `id` ascending. `id` ascending is always
         *       appended as a deterministic tiebreaker.
         *     - Filters (all optional, all whitelisted):
         *       - `requesterName` — case-insensitive substring match against the requester's name.
         *         Rows without a requester never match when this filter is set.
         *       - `subjectName` — case-insensitive substring match against the subject's name.
         *       - `providerName` — case-insensitive substring match against the provider's name.
         *       - `providerId` — exact match against the provider's user id. Combined with
         *         `view=received`, this scopes the list to feedbacks a specific person gave the caller.
         *       - `subjectId` — exact match against the subject's user id. Combined with
         *         `view=provided`, this scopes the list to feedbacks the caller gave a specific person.
         *       - `visibility` — exact match against the visibility enum.
         *       - `status` — exact match against the status enum.
         *       - `lastModified[gte]` — lower bound (inclusive) on `lastModified`, epoch
         *         milliseconds. Returns rows changed at or after this instant.
         *     - `content` is returned as `contentPreview`, capped at 200 characters; it is neither
         *       sortable nor filterable.
         *
         *     Malformed query parameters (unknown view, unknown sort field, unknown enum value,
         *     out-of-range page/pageSize) respond with `400` and a `ProblemDetail` body.
         */
        get: operations["listFeedbacks"];
        put?: never;
        /**
         * Create a feedback record
         * @description Any authenticated user may create a feedback record.
         */
        post: operations["createFeedback"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/feedbacks/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: components["parameters"]["ResourceId"];
            };
            cookie?: never;
        };
        /**
         * Fetch a feedback record
         * @description Authorization (`canReadFeedback`) is evaluated in this order — read access depends on the
         *     caller's relationship to the row, the `visibility` and (for subject/manager/public) the
         *     `status`:
         *     - ADMIN and the **provider** may always read, at any status/visibility.
         *     - the **requester** may read at any status, but only when `visibility` is
         *       `PROVIDER_REQUESTER` or `PROVIDER_REQUESTER_SUBJECT`.
         *     - the **subject** may read only when `visibility` is `PROVIDER_SUBJECT` or
         *       `PROVIDER_REQUESTER_SUBJECT` AND `status` is `SENT` or `WITHDRAWN` (so a `DRAFT`/
         *       `REQUESTED`/`REJECTED` record is not visible to the subject through this rule).
         *     - a **manager of the subject** may read any feedback about a subordinate, at any status
         *       (the endpoint grants a managing caller an unconditional read).
         *     - otherwise a `PUBLIC` record may be read by any authenticated user once `status` is `SENT`.
         *     Anything else is `403`.
         *
         *     Content redaction: a requester may see that a feedback they requested exists, but while it
         *     is unfinished (`DRAFT`/`REQUESTED`) the `content` field is returned as an empty string for
         *     that requester; it becomes visible once the feedback is sent. The field is therefore not
         *     guaranteed non-empty and is omitted from `required`.
         */
        get: operations["getFeedback"];
        /**
         * Replace a feedback record
         * @description Only the record's provider (or ADMIN) may modify a feedback. Status transitions
         *     (send / withdraw / pick-up / reject) are driven through this whole-resource `PUT` by
         *     changing `status`, rather than through action sub-resources — this is an intentional,
         *     settled design choice (notifications' `seen`/`unseen` actions are modelled differently on
         *     purpose) and should not be treated as spec drift.
         */
        put: operations["replaceFeedback"];
        post?: never;
        /**
         * Delete a feedback record
         * @description Soft-deletes a feedback (the row is flagged, not physically removed, and disappears from
         *     reads/lists). Only the record's **provider** may delete (ADMIN does not get feedback write
         *     access), and only while the feedback is in **DRAFT** status. If the feedback has a requester,
         *     they receive a notification that the provider deleted it (no link). The deletion is recorded
         *     in the feedback's audit history.
         */
        delete: operations["deleteFeedback"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/feedbacks/{id}/events": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: components["parameters"]["ResourceId"];
            };
            cookie?: never;
        };
        /**
         * List a feedback's audit history
         * @description Returns the immutable audit trail for a feedback — one entry per create, status transition
         *     and content/visibility edit — oldest first, each carrying the acting user and a generated
         *     description. Authorization matches the single-GET above (`canReadFeedback`, with a managing
         *     caller allowed): whoever may read the feedback may read its history. Events are
         *     server-generated; there is no create/update/delete endpoint.
         */
        get: operations["listFeedbackEvents"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/templates": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List templates
         * @description Lists templates. Any authenticated user may read.
         *
         *     Supports offset pagination, sorting and filtering.
         *
         *     - Sortable fields: `id`, `name`. Default sort is `id` ascending. `id` ascending is
         *       always appended as a deterministic tiebreaker.
         *     - Filter (optional, whitelisted):
         *       - `name` — case-insensitive substring match against the template name.
         *     - `content` is returned as `contentPreview`, capped at 200 characters; it is neither
         *       sortable nor filterable.
         *
         *     Malformed query parameters (unknown sort field, out-of-range page/pageSize) respond
         *     with `400` and a `ProblemDetail` body.
         */
        get: operations["listTemplates"];
        put?: never;
        /**
         * Create a template
         * @description ADMIN only.
         */
        post: operations["createTemplate"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/templates/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: components["parameters"]["ResourceId"];
            };
            cookie?: never;
        };
        /**
         * Fetch a template
         * @description Any authenticated user may read.
         */
        get: operations["getTemplate"];
        /**
         * Replace a template
         * @description ADMIN only.
         */
        put: operations["replaceTemplate"];
        post?: never;
        /**
         * Delete a template
         * @description ADMIN only.
         */
        delete: operations["deleteTemplate"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/notifications": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List the caller's notifications
         * @description Lists notifications addressed to the calling user (`recipientId` = caller). The list is
         *     always scoped to the caller, including for ADMIN — there is no cross-user view.
         *
         *     Notifications are generated as a side-effect of other activities; there is no create
         *     endpoint.
         *
         *     Supports offset pagination, sorting and filtering.
         *
         *     - Sortable fields: `id`, `timestamp`. Default sort is `timestamp` descending (newest
         *       first). `id` ascending is always appended as a deterministic tiebreaker.
         *     - Filter (optional, whitelisted):
         *       - `wasSeen` — `true`/`false`; restricts to seen / unseen notifications.
         *
         *     Malformed query parameters (unknown sort field, out-of-range page/pageSize, non-boolean
         *     `wasSeen`) respond with `400` and a `ProblemDetail` body.
         */
        get: operations["listNotifications"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/notifications/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: components["parameters"]["ResourceId"];
            };
            cookie?: never;
        };
        /**
         * Fetch a notification
         * @description The recipient or an ADMIN may read.
         */
        get: operations["getNotification"];
        put?: never;
        post?: never;
        /**
         * Delete a notification
         * @description The recipient or an ADMIN may delete.
         */
        delete: operations["deleteNotification"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/notifications/{id}/seen": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: components["parameters"]["ResourceId"];
            };
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Mark a notification as seen
         * @description Sets `wasSeen` to `true`. Idempotent. The recipient or an ADMIN may call it.
         */
        post: operations["markNotificationSeen"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/notifications/{id}/unseen": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: components["parameters"]["ResourceId"];
            };
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Mark a notification as unseen
         * @description Sets `wasSeen` to `false`. Idempotent. The recipient or an ADMIN may call it.
         */
        post: operations["markNotificationUnseen"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/notifications/seen-all": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Mark all of the caller's notifications as seen
         * @description Sets `wasSeen` to `true` for every one of the authenticated caller's still-unseen
         *     notifications, in a single request. Idempotent. Intrinsically scoped to the caller's own
         *     notifications (no `{id}`, no recipient guard); there is no ADMIN cross-user bypass.
         */
        post: operations["markAllNotificationsSeen"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        LoginRequest: {
            /** Format: email */
            email: string;
            password: string;
        };
        LoginResponse: {
            token: string;
            /**
             * Format: int64
             * @description Token expiry as Unix epoch milliseconds
             */
            expiresAt: number;
            /** Format: int64 */
            userId: number;
            /**
             * @description Global role of the authenticated user.
             * @enum {string}
             */
            role: "ADMIN" | "USER";
        };
        UserRequest: {
            name: string;
            /** Format: email */
            email: string;
            password: string;
            /**
             * @description Honoured only when the caller is ADMIN. Non-ADMIN callers must omit this
             *     field or send the value the user already has, otherwise the request is
             *     rejected with 403. Omitted on create defaults to USER.
             * @enum {string}
             */
            role?: "ADMIN" | "USER";
        };
        UserUpdateRequest: {
            name: string;
            /** Format: email */
            email: string;
            /**
             * @description Honoured only when the caller is ADMIN. Non-ADMIN callers must omit this
             *     field or send the value the user already has, otherwise the request is
             *     rejected with 403. Omitting it keeps the user's current role.
             * @enum {string}
             */
            role?: "ADMIN" | "USER";
        };
        PasswordUpdateRequest: {
            password: string;
        };
        UserResponse: {
            /** Format: int64 */
            id: number;
            name: string;
            /** Format: email */
            email: string;
            /**
             * @description Global role.
             * @enum {string}
             */
            role: "ADMIN" | "USER";
        };
        UserPage: {
            items: components["schemas"]["UserResponse"][];
            page: number;
            pageSize: number;
            /**
             * Format: int64
             * @description Row count after filters, before pagination.
             */
            total: number;
        };
        TeamRequest: {
            name: string;
            /** Format: int64 */
            managerId: number;
            /**
             * @description Defaults to an empty list when omitted. Zero-member teams are allowed;
             *     members can be added later via the `/api/v1/teams/{id}/members/{userId}` sub-resource.
             */
            memberIds?: number[];
        };
        TeamResponse: {
            /** Format: int64 */
            id: number;
            name: string;
            /** Format: int64 */
            managerId: number;
            memberIds: number[];
        };
        TeamListItem: {
            /** Format: int64 */
            id: number;
            name: string;
            /** Format: int64 */
            managerId: number;
            managerName: string;
            /** @description True when the user referenced by `managerId` has been soft-deleted. */
            managerDeleted: boolean;
        };
        TeamPage: {
            items: components["schemas"]["TeamListItem"][];
            page: number;
            pageSize: number;
            /**
             * Format: int64
             * @description Row count after filters, before pagination.
             */
            total: number;
        };
        TeamMemberListItem: {
            /** Format: int64 */
            userId: number;
            name: string;
            /** Format: email */
            email: string;
            /** Format: int64 */
            teamId: number;
            teamName: string;
        };
        TeamMemberPage: {
            items: components["schemas"]["TeamMemberListItem"][];
            page: number;
            pageSize: number;
            /**
             * Format: int64
             * @description Row count after filters, before pagination.
             */
            total: number;
        };
        FeedbackRequest: {
            /** Format: int64 */
            requesterId?: number | null;
            /** Format: int64 */
            subjectId: number;
            /** Format: int64 */
            providerId: number;
            /** @enum {string} */
            visibility: "PROVIDER_SUBJECT" | "PROVIDER_REQUESTER" | "PROVIDER_REQUESTER_SUBJECT" | "PUBLIC";
            /** @enum {string} */
            status: "REQUESTED" | "DRAFT" | "SENT" | "WITHDRAWN" | "REJECTED";
            /** @default  */
            content: string;
            /**
             * @description Requester's clarification note to the provider (why they asked, what they expect).
             *     Captured only when a feedback is created; immutable afterward — any value sent on
             *     update (`PUT`) is ignored.
             */
            requesterMessage?: string | null;
        };
        FeedbackResponse: {
            /** Format: int64 */
            id: number;
            /** Format: int64 */
            requesterId?: number | null;
            /** Format: int64 */
            subjectId: number;
            /** Format: int64 */
            providerId: number;
            /** @enum {string} */
            visibility: "PROVIDER_SUBJECT" | "PROVIDER_REQUESTER" | "PROVIDER_REQUESTER_SUBJECT" | "PUBLIC";
            /** @enum {string} */
            status: "REQUESTED" | "DRAFT" | "SENT" | "WITHDRAWN" | "REJECTED";
            /**
             * @description The feedback body. Returned as an empty string (and omitted from `required`)
             *     when the caller may see that the record exists but not its content — a requester
             *     watching an unfinished (`DRAFT`/`REQUESTED`) feedback they requested.
             */
            content?: string;
            /**
             * @description Requester's clarification note to the provider, set at creation and never editable.
             *     Null when the requester left it empty.
             */
            requesterMessage?: string | null;
            /**
             * Format: int64
             * @description Epoch milliseconds of the last change. Server-managed and read-only.
             */
            lastModified: number;
            /** @description Display name of the requester; null when there is no requester. Server-resolved, read-only. */
            requesterName?: string | null;
            /** @description Display name of the subject. Server-resolved, read-only. */
            subjectName?: string | null;
            /** @description Display name of the provider. Server-resolved, read-only. */
            providerName?: string | null;
        };
        FeedbackListItem: {
            /** Format: int64 */
            id: number;
            /** Format: int64 */
            requesterId?: number | null;
            /** @description Null when the record has no requester. */
            requesterName?: string | null;
            /** @description True when the user referenced by `requesterId` has been soft-deleted. False when there is no requester. */
            requesterDeleted: boolean;
            /** Format: int64 */
            subjectId: number;
            subjectName: string;
            /** @description True when the user referenced by `subjectId` has been soft-deleted. */
            subjectDeleted: boolean;
            /** Format: int64 */
            providerId: number;
            providerName: string;
            /** @description True when the user referenced by `providerId` has been soft-deleted. */
            providerDeleted: boolean;
            /** @enum {string} */
            visibility: "PROVIDER_SUBJECT" | "PROVIDER_REQUESTER" | "PROVIDER_REQUESTER_SUBJECT" | "PUBLIC";
            /** @enum {string} */
            status: "REQUESTED" | "DRAFT" | "SENT" | "WITHDRAWN" | "REJECTED";
            /** @description First 200 characters of `content`. */
            contentPreview: string;
            /**
             * Format: int64
             * @description Epoch milliseconds of the last change. Server-managed and read-only.
             */
            lastModified: number;
        };
        FeedbackPage: {
            items: components["schemas"]["FeedbackListItem"][];
            page: number;
            pageSize: number;
            /**
             * Format: int64
             * @description Row count after filters, before pagination.
             */
            total: number;
        };
        TemplateRequest: {
            name: string;
            /** @default  */
            content: string;
        };
        TemplateResponse: {
            /** Format: int64 */
            id: number;
            name: string;
            content: string;
        };
        TemplateListItem: {
            /** Format: int64 */
            id: number;
            name: string;
            /** @description First 200 characters of `content`. */
            contentPreview: string;
        };
        TemplatePage: {
            items: components["schemas"]["TemplateListItem"][];
            page: number;
            pageSize: number;
            /**
             * Format: int64
             * @description Row count after filters, before pagination.
             */
            total: number;
        };
        FeedbackEventResponse: {
            /** Format: int64 */
            id: number;
            /** Format: int64 */
            feedbackId: number;
            /** Format: int64 */
            userId: number;
            /** @description Display name of the user who performed the change. Server-resolved, read-only. */
            userName: string;
            /**
             * Format: int64
             * @description Epoch milliseconds when the event was recorded. Server-managed.
             */
            timestamp: number;
            /** @description Human-readable description of what changed. */
            content: string;
        };
        FeedbackEventList: {
            items: components["schemas"]["FeedbackEventResponse"][];
        };
        NotificationResponse: {
            /** Format: int64 */
            id: number;
            /** Format: int64 */
            recipientId: number;
            /**
             * Format: int64
             * @description Epoch milliseconds when the notification was generated. Server-managed.
             */
            timestamp: number;
            message: string;
            /** @description Optional in-app path to open from the notification; absent when there is nowhere to go. */
            link?: string | null;
            /** @description Whether the recipient has marked the notification as seen. */
            wasSeen: boolean;
        };
        NotificationPage: {
            items: components["schemas"]["NotificationResponse"][];
            page: number;
            pageSize: number;
            /**
             * Format: int64
             * @description Row count after filters, before pagination.
             */
            total: number;
        };
        /** @description RFC 7807 problem detail. Served as `application/problem+json`. */
        ProblemDetail: {
            /**
             * @description A URI reference identifying the problem type.
             * @default about:blank
             */
            type: string;
            /** @description Short, human-readable summary of the problem type. */
            title: string;
            /** @description HTTP status code. */
            status: number;
            /** @description Human-readable explanation specific to this occurrence. */
            detail?: string;
            /** @description A URI reference identifying the specific occurrence. */
            instance?: string;
        };
    };
    responses: {
        /** @description Malformed request */
        BadRequest: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/problem+json": components["schemas"]["ProblemDetail"];
            };
        };
        /** @description Missing or invalid token */
        Unauthorized: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/problem+json": components["schemas"]["ProblemDetail"];
            };
        };
        /** @description Caller is not permitted to perform this action */
        Forbidden: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/problem+json": components["schemas"]["ProblemDetail"];
            };
        };
        /** @description Resource not found */
        NotFound: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/problem+json": components["schemas"]["ProblemDetail"];
            };
        };
        /** @description Conflict with an existing resource */
        Conflict: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/problem+json": components["schemas"]["ProblemDetail"];
            };
        };
        /** @description Rate limit exceeded */
        TooManyRequests: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/problem+json": components["schemas"]["ProblemDetail"];
            };
        };
        /** @description Unexpected server error */
        InternalServerError: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/problem+json": components["schemas"]["ProblemDetail"];
            };
        };
    };
    parameters: {
        ResourceId: number;
        UserIdInPath: number;
        /** @description 1-based page index. Defaults to 1. */
        Page: number;
        /** @description Rows per page. Defaults to 20, maximum 100. */
        PageSize: number;
        /**
         * @description Sort spec. Format: `field` (ascending) or `-field` (descending). Multiple fields are
         *     comma-separated, leftmost wins: `sort=-createdAt,id`. The endpoint declares its
         *     sortable-field whitelist; unknown fields are rejected with `400`. `id` ascending is
         *     always appended as a deterministic tiebreaker.
         */
        Sort: string;
    };
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    login: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["LoginRequest"];
            };
        };
        responses: {
            /** @description Token issued */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["LoginResponse"];
                };
            };
            401: components["responses"]["Unauthorized"];
            429: components["responses"]["TooManyRequests"];
            500: components["responses"]["InternalServerError"];
        };
    };
    logout: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Token revoked */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            401: components["responses"]["Unauthorized"];
            500: components["responses"]["InternalServerError"];
        };
    };
    listUsers: {
        parameters: {
            query?: {
                /** @description 1-based page index. Defaults to 1. */
                page?: components["parameters"]["Page"];
                /** @description Rows per page. Defaults to 20, maximum 100. */
                pageSize?: components["parameters"]["PageSize"];
                /**
                 * @description Sort spec. Format: `field` (ascending) or `-field` (descending). Multiple fields are
                 *     comma-separated, leftmost wins: `sort=-createdAt,id`. The endpoint declares its
                 *     sortable-field whitelist; unknown fields are rejected with `400`. `id` ascending is
                 *     always appended as a deterministic tiebreaker.
                 */
                sort?: components["parameters"]["Sort"];
                /** @description Case-insensitive substring match against the user's name. */
                name?: string;
                /** @description Case-insensitive substring match against the user's email. */
                email?: string;
                /** @description Exact match against the user's global role. */
                role?: "ADMIN" | "USER";
                /** @description Filter to users who are members of the given team. */
                teamId?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description A page of users */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UserPage"];
                };
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthorized"];
            500: components["responses"]["InternalServerError"];
        };
    };
    createUser: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UserRequest"];
            };
        };
        responses: {
            /** @description Created */
            201: {
                headers: {
                    /** @description URL of the new user resource */
                    Location?: string;
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UserResponse"];
                };
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthorized"];
            /** @description Caller is not ADMIN */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ProblemDetail"];
                };
            };
            /** @description Email already in use */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ProblemDetail"];
                };
            };
            500: components["responses"]["InternalServerError"];
        };
    };
    getUser: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: components["parameters"]["ResourceId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UserResponse"];
                };
            };
            401: components["responses"]["Unauthorized"];
            /** @description Caller is not the target user and not ADMIN */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ProblemDetail"];
                };
            };
            404: components["responses"]["NotFound"];
            500: components["responses"]["InternalServerError"];
        };
    };
    deleteUser: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: components["parameters"]["ResourceId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Deleted */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            401: components["responses"]["Unauthorized"];
            /** @description Caller is not ADMIN */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ProblemDetail"];
                };
            };
            404: components["responses"]["NotFound"];
            500: components["responses"]["InternalServerError"];
        };
    };
    patchUser: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: components["parameters"]["ResourceId"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UserUpdateRequest"];
            };
        };
        responses: {
            /** @description Updated */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            401: components["responses"]["Unauthorized"];
            /** @description Caller is not the target user and not ADMIN, or attempted to escalate role */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ProblemDetail"];
                };
            };
            404: components["responses"]["NotFound"];
            /** @description Email already in use by another user */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ProblemDetail"];
                };
            };
            500: components["responses"]["InternalServerError"];
        };
    };
    changeUserPassword: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: components["parameters"]["ResourceId"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["PasswordUpdateRequest"];
            };
        };
        responses: {
            /** @description Password updated */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            401: components["responses"]["Unauthorized"];
            /** @description Caller is not the target user and not ADMIN */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ProblemDetail"];
                };
            };
            404: components["responses"]["NotFound"];
            500: components["responses"]["InternalServerError"];
        };
    };
    listTeams: {
        parameters: {
            query?: {
                /** @description 1-based page index. Defaults to 1. */
                page?: components["parameters"]["Page"];
                /** @description Rows per page. Defaults to 20, maximum 100. */
                pageSize?: components["parameters"]["PageSize"];
                /**
                 * @description Sort spec. Format: `field` (ascending) or `-field` (descending). Multiple fields are
                 *     comma-separated, leftmost wins: `sort=-createdAt,id`. The endpoint declares its
                 *     sortable-field whitelist; unknown fields are rejected with `400`. `id` ascending is
                 *     always appended as a deterministic tiebreaker.
                 */
                sort?: components["parameters"]["Sort"];
                /** @description Case-insensitive substring match against the team's name. */
                name?: string;
                /** @description Exact match against the team's manager id. */
                managerId?: number;
                /** @description Filter to teams the given user is a member of. */
                memberId?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description A page of teams */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TeamPage"];
                };
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthorized"];
            500: components["responses"]["InternalServerError"];
        };
    };
    createTeam: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["TeamRequest"];
            };
        };
        responses: {
            /** @description Created */
            201: {
                headers: {
                    /** @description URL of the new team resource */
                    Location?: string;
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TeamResponse"];
                };
            };
            /** @description Validation error (e.g. manager in member list, duplicate members, referenced user does not exist) */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ProblemDetail"];
                };
            };
            401: components["responses"]["Unauthorized"];
            /** @description Caller attempted to set `managerId` to another user without being ADMIN */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ProblemDetail"];
                };
            };
            500: components["responses"]["InternalServerError"];
        };
    };
    listTeamMembers: {
        parameters: {
            query?: {
                /** @description 1-based page index. Defaults to 1. */
                page?: components["parameters"]["Page"];
                /** @description Rows per page. Defaults to 20, maximum 100. */
                pageSize?: components["parameters"]["PageSize"];
                /**
                 * @description Sort spec. Format: `field` (ascending) or `-field` (descending). Multiple fields are
                 *     comma-separated, leftmost wins: `sort=-createdAt,id`. The endpoint declares its
                 *     sortable-field whitelist; unknown fields are rejected with `400`. `id` ascending is
                 *     always appended as a deterministic tiebreaker.
                 */
                sort?: components["parameters"]["Sort"];
                /**
                 * @description Which caller-relative slice to list.
                 *     - `member`: members of teams the caller belongs to.
                 *     - `managed`: members of teams the caller manages.
                 *     - `managers`: the managers of teams the caller is a member of. Each item's
                 *       `userId`/`name`/`email` describe the manager and `teamId`/`teamName` the
                 *       managed team. The caller is excluded; a manager who manages several of the
                 *       caller's teams appears once per team.
                 */
                view?: "member" | "managed" | "managers";
                /** @description Case-insensitive substring match against the member's name. */
                name?: string;
                /** @description Case-insensitive substring match against the member's email. */
                email?: string;
                /** @description Exact match against the team's id. */
                teamId?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description A page of team members */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TeamMemberPage"];
                };
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthorized"];
            500: components["responses"]["InternalServerError"];
        };
    };
    getTeam: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: components["parameters"]["ResourceId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TeamResponse"];
                };
            };
            401: components["responses"]["Unauthorized"];
            404: components["responses"]["NotFound"];
            500: components["responses"]["InternalServerError"];
        };
    };
    replaceTeam: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: components["parameters"]["ResourceId"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["TeamRequest"];
            };
        };
        responses: {
            /** @description Updated */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation error (e.g. referenced user does not exist) */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ProblemDetail"];
                };
            };
            401: components["responses"]["Unauthorized"];
            /** @description Caller is not the team's manager and not ADMIN */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ProblemDetail"];
                };
            };
            404: components["responses"]["NotFound"];
            500: components["responses"]["InternalServerError"];
        };
    };
    deleteTeam: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: components["parameters"]["ResourceId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Deleted */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            401: components["responses"]["Unauthorized"];
            /** @description Caller is not the team's manager and not ADMIN */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ProblemDetail"];
                };
            };
            404: components["responses"]["NotFound"];
            500: components["responses"]["InternalServerError"];
        };
    };
    addTeamMember: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: components["parameters"]["ResourceId"];
                userId: components["parameters"]["UserIdInPath"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Member added (or already present) */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation error (e.g. adding the manager as a member, referenced user does not exist) */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ProblemDetail"];
                };
            };
            401: components["responses"]["Unauthorized"];
            /** @description Caller is not the team's manager and not ADMIN */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ProblemDetail"];
                };
            };
            404: components["responses"]["NotFound"];
            500: components["responses"]["InternalServerError"];
        };
    };
    removeTeamMember: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: components["parameters"]["ResourceId"];
                userId: components["parameters"]["UserIdInPath"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Removed */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Cannot remove the last member or the manager via this endpoint */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ProblemDetail"];
                };
            };
            401: components["responses"]["Unauthorized"];
            /** @description Caller is not the team's manager and not ADMIN */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ProblemDetail"];
                };
            };
            404: components["responses"]["NotFound"];
            500: components["responses"]["InternalServerError"];
        };
    };
    listFeedbacks: {
        parameters: {
            query?: {
                /** @description 1-based page index. Defaults to 1. */
                page?: components["parameters"]["Page"];
                /** @description Rows per page. Defaults to 20, maximum 100. */
                pageSize?: components["parameters"]["PageSize"];
                /**
                 * @description Sort spec. Format: `field` (ascending) or `-field` (descending). Multiple fields are
                 *     comma-separated, leftmost wins: `sort=-createdAt,id`. The endpoint declares its
                 *     sortable-field whitelist; unknown fields are rejected with `400`. `id` ascending is
                 *     always appended as a deterministic tiebreaker.
                 */
                sort?: components["parameters"]["Sort"];
                /** @description Which caller-relative slice of feedbacks to list. */
                view?: "received" | "provided" | "team";
                /** @description Case-insensitive substring match against the requester's name. */
                requesterName?: string;
                /** @description Case-insensitive substring match against the subject's name. */
                subjectName?: string;
                /** @description Case-insensitive substring match against the provider's name. */
                providerName?: string;
                /** @description Exact match against the provider's user id. */
                providerId?: number;
                /** @description Exact match against the subject's user id. */
                subjectId?: number;
                /** @description Exact match against the record's visibility. */
                visibility?: "PROVIDER_SUBJECT" | "PROVIDER_REQUESTER" | "PROVIDER_REQUESTER_SUBJECT" | "PUBLIC";
                /** @description Exact match against the record's status. */
                status?: "REQUESTED" | "DRAFT" | "SENT" | "WITHDRAWN" | "REJECTED";
                /** @description Lower bound (inclusive) on `lastModified`, epoch milliseconds. Returns rows changed at or after this instant. */
                "lastModified[gte]"?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description A page of feedbacks */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["FeedbackPage"];
                };
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthorized"];
            500: components["responses"]["InternalServerError"];
        };
    };
    createFeedback: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["FeedbackRequest"];
            };
        };
        responses: {
            /** @description Created */
            201: {
                headers: {
                    /** @description URL of the new feedback resource */
                    Location?: string;
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["FeedbackResponse"];
                };
            };
            /** @description Validation error (provider ≠ subject; requester ≠ provider; REQUESTED requires a requester; a feedback with a requester may not use PROVIDER_SUBJECT visibility) or referenced user does not exist */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ProblemDetail"];
                };
            };
            401: components["responses"]["Unauthorized"];
            /** @description Caller is not a party (provider or requester) to the feedback and not ADMIN */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ProblemDetail"];
                };
            };
            500: components["responses"]["InternalServerError"];
        };
    };
    getFeedback: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: components["parameters"]["ResourceId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["FeedbackResponse"];
                };
            };
            401: components["responses"]["Unauthorized"];
            /** @description Caller's relationship to the row does not satisfy `visibility` */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ProblemDetail"];
                };
            };
            404: components["responses"]["NotFound"];
            500: components["responses"]["InternalServerError"];
        };
    };
    replaceFeedback: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: components["parameters"]["ResourceId"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["FeedbackRequest"];
            };
        };
        responses: {
            /** @description Updated */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation error (same invariants as create — incl. a feedback with a requester may not use PROVIDER_SUBJECT visibility) or invalid status transition */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ProblemDetail"];
                };
            };
            401: components["responses"]["Unauthorized"];
            /** @description Caller is not the feedback's provider and not ADMIN */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ProblemDetail"];
                };
            };
            404: components["responses"]["NotFound"];
            500: components["responses"]["InternalServerError"];
        };
    };
    deleteFeedback: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: components["parameters"]["ResourceId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Deleted */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Feedback is not in DRAFT status (only drafts may be deleted) */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ProblemDetail"];
                };
            };
            401: components["responses"]["Unauthorized"];
            /** @description Caller is not the feedback's provider */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ProblemDetail"];
                };
            };
            404: components["responses"]["NotFound"];
            500: components["responses"]["InternalServerError"];
        };
    };
    listFeedbackEvents: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: components["parameters"]["ResourceId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The feedback's events, oldest first */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["FeedbackEventList"];
                };
            };
            401: components["responses"]["Unauthorized"];
            /** @description Caller may not read this feedback */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ProblemDetail"];
                };
            };
            404: components["responses"]["NotFound"];
            500: components["responses"]["InternalServerError"];
        };
    };
    listTemplates: {
        parameters: {
            query?: {
                /** @description 1-based page index. Defaults to 1. */
                page?: components["parameters"]["Page"];
                /** @description Rows per page. Defaults to 20, maximum 100. */
                pageSize?: components["parameters"]["PageSize"];
                /**
                 * @description Sort spec. Format: `field` (ascending) or `-field` (descending). Multiple fields are
                 *     comma-separated, leftmost wins: `sort=-createdAt,id`. The endpoint declares its
                 *     sortable-field whitelist; unknown fields are rejected with `400`. `id` ascending is
                 *     always appended as a deterministic tiebreaker.
                 */
                sort?: components["parameters"]["Sort"];
                /** @description Case-insensitive substring match against the template name. */
                name?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description A page of templates */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TemplatePage"];
                };
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthorized"];
            500: components["responses"]["InternalServerError"];
        };
    };
    createTemplate: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["TemplateRequest"];
            };
        };
        responses: {
            /** @description Created */
            201: {
                headers: {
                    /** @description URL of the new template resource */
                    Location?: string;
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TemplateResponse"];
                };
            };
            /** @description Validation error (e.g. blank name) */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ProblemDetail"];
                };
            };
            401: components["responses"]["Unauthorized"];
            /** @description Caller is not ADMIN */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ProblemDetail"];
                };
            };
            /** @description A template with the same name already exists */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ProblemDetail"];
                };
            };
            500: components["responses"]["InternalServerError"];
        };
    };
    getTemplate: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: components["parameters"]["ResourceId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TemplateResponse"];
                };
            };
            401: components["responses"]["Unauthorized"];
            404: components["responses"]["NotFound"];
            500: components["responses"]["InternalServerError"];
        };
    };
    replaceTemplate: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: components["parameters"]["ResourceId"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["TemplateRequest"];
            };
        };
        responses: {
            /** @description Updated */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation error (e.g. blank name) */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ProblemDetail"];
                };
            };
            401: components["responses"]["Unauthorized"];
            /** @description Caller is not ADMIN */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ProblemDetail"];
                };
            };
            404: components["responses"]["NotFound"];
            /** @description A template with the same name already exists */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ProblemDetail"];
                };
            };
            500: components["responses"]["InternalServerError"];
        };
    };
    deleteTemplate: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: components["parameters"]["ResourceId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Deleted */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            401: components["responses"]["Unauthorized"];
            /** @description Caller is not ADMIN */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ProblemDetail"];
                };
            };
            404: components["responses"]["NotFound"];
            500: components["responses"]["InternalServerError"];
        };
    };
    listNotifications: {
        parameters: {
            query?: {
                /** @description 1-based page index. Defaults to 1. */
                page?: components["parameters"]["Page"];
                /** @description Rows per page. Defaults to 20, maximum 100. */
                pageSize?: components["parameters"]["PageSize"];
                /**
                 * @description Sort spec. Format: `field` (ascending) or `-field` (descending). Multiple fields are
                 *     comma-separated, leftmost wins: `sort=-createdAt,id`. The endpoint declares its
                 *     sortable-field whitelist; unknown fields are rejected with `400`. `id` ascending is
                 *     always appended as a deterministic tiebreaker.
                 */
                sort?: components["parameters"]["Sort"];
                /** @description Restrict to seen (`true`) or unseen (`false`) notifications. */
                wasSeen?: boolean;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description A page of notifications */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["NotificationPage"];
                };
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthorized"];
            500: components["responses"]["InternalServerError"];
        };
    };
    getNotification: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: components["parameters"]["ResourceId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["NotificationResponse"];
                };
            };
            401: components["responses"]["Unauthorized"];
            /** @description Caller is neither the recipient nor ADMIN */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ProblemDetail"];
                };
            };
            404: components["responses"]["NotFound"];
            500: components["responses"]["InternalServerError"];
        };
    };
    deleteNotification: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: components["parameters"]["ResourceId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Deleted */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            401: components["responses"]["Unauthorized"];
            /** @description Caller is neither the recipient nor ADMIN */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ProblemDetail"];
                };
            };
            404: components["responses"]["NotFound"];
            500: components["responses"]["InternalServerError"];
        };
    };
    markNotificationSeen: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: components["parameters"]["ResourceId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Marked as seen */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            401: components["responses"]["Unauthorized"];
            /** @description Caller is neither the recipient nor ADMIN */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ProblemDetail"];
                };
            };
            404: components["responses"]["NotFound"];
            500: components["responses"]["InternalServerError"];
        };
    };
    markNotificationUnseen: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: components["parameters"]["ResourceId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Marked as unseen */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            401: components["responses"]["Unauthorized"];
            /** @description Caller is neither the recipient nor ADMIN */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ProblemDetail"];
                };
            };
            404: components["responses"]["NotFound"];
            500: components["responses"]["InternalServerError"];
        };
    };
    markAllNotificationsSeen: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description All of the caller's notifications marked as seen */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            401: components["responses"]["Unauthorized"];
            500: components["responses"]["InternalServerError"];
        };
    };
}
