/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/login": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Exchange credentials for a JWT */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["LoginRequest"];
                };
            };
            responses: {
                /** @description Token issued */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["LoginResponse"];
                    };
                };
                /** @description Unknown email or wrong password */
                401: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/logout": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Revoke the bearer token (server-side denylist) */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Token revoked */
                204: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                /** @description Missing or invalid token */
                401: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/users": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List users
         * @description Any authenticated user may list. Supports offset pagination, sorting and filtering.
         *
         *     - Sortable fields: `id`, `name`, `email`, `role`. Default sort is `id` ascending.
         *       `id` ascending is always appended as a deterministic tiebreaker.
         *     - Filters (all optional, all whitelisted):
         *       - `name` — case-insensitive substring match against `name`.
         *       - `email` — case-insensitive substring match against `email`.
         *       - `role` — exact match, `ADMIN` or `USER`.
         *       - `teamId` — restrict to users who are members of the given team.
         *     - The `q` free-text param defined elsewhere is not used by this endpoint.
         *
         *     Malformed query parameters (unknown sort field, unknown role, out-of-range page/pageSize)
         *     respond with `400` and an `ApiError` body.
         */
        get: {
            parameters: {
                query?: {
                    /** @description 1-based page index. Defaults to 1. */
                    page?: components["parameters"]["Page"];
                    /** @description Rows per page. Defaults to 20, maximum 100. */
                    pageSize?: components["parameters"]["PageSize"];
                    /**
                     * @description Sort spec. Format: `field` (ascending) or `-field` (descending). Multiple fields are
                     *     comma-separated, leftmost wins: `sort=-createdAt,id`. The endpoint declares its
                     *     sortable-field whitelist; unknown fields are rejected with `400`. `id` ascending is
                     *     always appended as a deterministic tiebreaker.
                     */
                    sort?: components["parameters"]["Sort"];
                    /** @description Case-insensitive substring match against the user's name. */
                    name?: string;
                    /** @description Case-insensitive substring match against the user's email. */
                    email?: string;
                    /** @description Exact match against the user's global role. */
                    role?: "ADMIN" | "USER";
                    /** @description Filter to users who are members of the given team. */
                    teamId?: number;
                };
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description A page of users */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["UserPage"];
                    };
                };
                /** @description Malformed query parameters */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ApiError"];
                    };
                };
                /** @description Missing or invalid token */
                401: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ApiError"];
                    };
                };
            };
        };
        put?: never;
        /**
         * Create a user
         * @description Requires ADMIN. If the request body omits `role`, the new user defaults to `USER`.
         */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["UserRequest"];
                };
            };
            responses: {
                /** @description Created */
                201: {
                    headers: {
                        /** @description URL of the new user resource */
                        Location?: string;
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["UserResponse"];
                    };
                };
                /** @description Missing or invalid token */
                401: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ApiError"];
                    };
                };
                /** @description Caller is not ADMIN */
                403: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ApiError"];
                    };
                };
                /** @description Email already in use */
                409: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ApiError"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/users/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: components["parameters"]["UserId"];
            };
            cookie?: never;
        };
        /**
         * Fetch a user by id
         * @description Requires the caller to be the target user, or to be ADMIN.
         */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: components["parameters"]["UserId"];
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["UserResponse"];
                    };
                };
                /** @description Missing or invalid token */
                401: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                /** @description Caller is not the target user and not ADMIN */
                403: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ApiError"];
                    };
                };
                /** @description Not found */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        /**
         * Update a user
         * @description Updates a user's `name`, `email`, and `role`. The password cannot be
         *     changed via this endpoint and the existing password is preserved.
         *     Requires the caller to be the target user, or to be ADMIN.
         *     Only ADMIN may change a user's `role`; a non-ADMIN caller must either
         *     omit `role` or send the value the user already has, otherwise the request is rejected with 403.
         */
        put: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: components["parameters"]["UserId"];
                };
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["UserUpdateRequest"];
                };
            };
            responses: {
                /** @description Updated */
                204: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                /** @description Missing or invalid token */
                401: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                /** @description Caller is not the target user and not ADMIN */
                403: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ApiError"];
                    };
                };
                /** @description Not found */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                /** @description Email already in use by another user */
                409: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ApiError"];
                    };
                };
            };
        };
        post?: never;
        /**
         * Delete a user
         * @description Requires ADMIN.
         */
        delete: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: components["parameters"]["UserId"];
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Deleted */
                204: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                /** @description Missing or invalid token */
                401: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                /** @description Caller is not ADMIN */
                403: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ApiError"];
                    };
                };
            };
        };
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/users/{id}/password": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: components["parameters"]["UserId"];
            };
            cookie?: never;
        };
        get?: never;
        /**
         * Change a user's password
         * @description Sets a new password for the user. Only the password is changed; no other
         *     fields are touched. Requires the caller to be the target user, or to be ADMIN.
         */
        put: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: components["parameters"]["UserId"];
                };
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["PasswordUpdateRequest"];
                };
            };
            responses: {
                /** @description Password updated */
                204: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                /** @description Missing or invalid token */
                401: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                /** @description Caller is not the target user and not ADMIN */
                403: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ApiError"];
                    };
                };
                /** @description Not found */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/teams": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List teams
         * @description Any authenticated user may list. Supports offset pagination, sorting, and filtering.
         *
         *     - Sortable fields: `id`, `name`. Default sort is `id` ascending; `id` ascending
         *       is always appended as a deterministic tiebreaker.
         *     - Filters (all optional):
         *       - `name` — case-insensitive substring match against the team's name.
         *       - `managerId` — exact match against the team's manager id.
         *       - `memberId` — restrict to teams the given user is a member of.
         *
         *     Each returned item includes the manager's `name` resolved via join so the UI
         *     does not need an N+1 lookup.
         *
         *     Malformed query parameters (unknown sort field, non-numeric managerId,
         *     out-of-range page/pageSize) respond with `400` and an `ApiError` body.
         */
        get: {
            parameters: {
                query?: {
                    /** @description 1-based page index. Defaults to 1. */
                    page?: components["parameters"]["Page"];
                    /** @description Rows per page. Defaults to 20, maximum 100. */
                    pageSize?: components["parameters"]["PageSize"];
                    /**
                     * @description Sort spec. Format: `field` (ascending) or `-field` (descending). Multiple fields are
                     *     comma-separated, leftmost wins: `sort=-createdAt,id`. The endpoint declares its
                     *     sortable-field whitelist; unknown fields are rejected with `400`. `id` ascending is
                     *     always appended as a deterministic tiebreaker.
                     */
                    sort?: components["parameters"]["Sort"];
                    /** @description Case-insensitive substring match against the team's name. */
                    name?: string;
                    /** @description Exact match against the team's manager id. */
                    managerId?: number;
                    /** @description Filter to teams the given user is a member of. */
                    memberId?: number;
                };
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description A page of teams */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["TeamPage"];
                    };
                };
                /** @description Malformed query parameters */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ApiError"];
                    };
                };
                /** @description Missing or invalid token */
                401: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ApiError"];
                    };
                };
            };
        };
        put?: never;
        /**
         * Create a team
         * @description Any authenticated user may create a team, but the `managerId` in
         *     the request body must equal the caller's own user id (ADMIN may
         *     designate any user).
         */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["TeamRequest"];
                };
            };
            responses: {
                /** @description Created */
                201: {
                    headers: {
                        Location?: string;
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["TeamResponse"];
                    };
                };
                /** @description Validation error (e.g. manager in member list */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                /** @description Missing or invalid token */
                401: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                /** @description Caller attempted to set `managerId` to another user without being ADMIN */
                403: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ApiError"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/teams/members": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List members of the caller's teams
         * @description Lists team members scoped by `view`. Scoping is always relative to the caller,
         *     including ADMIN callers.
         *
         *     - `view=member` (the default): members of teams where the caller is a member.
         *       The caller's own rows are excluded. Team managers never appear — a manager is
         *       not a `team_members` row.
         *     - `view=managed`: members of teams where the caller is the manager.
         *     - `view=managers`: the managers of teams where the caller is a member. Each item
         *       describes a manager (in `userId`/`name`/`email`) and the managed team. The
         *       caller is excluded.
         *
         *     Each item is one (user, team) pair — a user who shares several teams with the
         *     caller appears once per team. Soft-deleted users and soft-deleted teams are
         *     excluded.
         *
         *     Supports offset pagination, sorting and filtering.
         *
         *     - Sortable fields: `id` (the member's user id), `name`, `email`, `teamName`.
         *       Default sort is `id` ascending. `id` ascending and the team id ascending are
         *       always appended as deterministic tiebreakers.
         *     - Filters (all optional, all whitelisted):
         *       - `name` — case-insensitive substring match against the member's name.
         *       - `email` — case-insensitive substring match against the member's email.
         *       - `teamId` — exact match against the team's id.
         *
         *     Malformed query parameters (unknown view, unknown sort field, non-numeric
         *     teamId, out-of-range page/pageSize) respond with `400` and an `ApiError` body.
         */
        get: {
            parameters: {
                query?: {
                    /** @description 1-based page index. Defaults to 1. */
                    page?: components["parameters"]["Page"];
                    /** @description Rows per page. Defaults to 20, maximum 100. */
                    pageSize?: components["parameters"]["PageSize"];
                    /**
                     * @description Sort spec. Format: `field` (ascending) or `-field` (descending). Multiple fields are
                     *     comma-separated, leftmost wins: `sort=-createdAt,id`. The endpoint declares its
                     *     sortable-field whitelist; unknown fields are rejected with `400`. `id` ascending is
                     *     always appended as a deterministic tiebreaker.
                     */
                    sort?: components["parameters"]["Sort"];
                    /**
                     * @description Which caller-relative slice to list.
                     *     - `member`: members of teams the caller belongs to.
                     *     - `managed`: members of teams the caller manages.
                     *     - `managers`: the managers of teams the caller is a member of. Each item's
                     *       `userId`/`name`/`email` describe the manager and `teamId`/`teamName` the
                     *       managed team. The caller is excluded; a manager who manages several of the
                     *       caller's teams appears once per team.
                     */
                    view?: "member" | "managed" | "managers";
                    /** @description Case-insensitive substring match against the member's name. */
                    name?: string;
                    /** @description Case-insensitive substring match against the member's email. */
                    email?: string;
                    /** @description Exact match against the team's id. */
                    teamId?: number;
                };
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description A page of team members */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["TeamMemberPage"];
                    };
                };
                /** @description Malformed query parameters */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ApiError"];
                    };
                };
                /** @description Missing or invalid token */
                401: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ApiError"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/teams/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: components["parameters"]["TeamId"];
            };
            cookie?: never;
        };
        /**
         * Fetch a team
         * @description Any authenticated user may read.
         */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: components["parameters"]["TeamId"];
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["TeamResponse"];
                    };
                };
                /** @description Missing or invalid token */
                401: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                /** @description Not found */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        /**
         * Replace a team
         * @description Requires the caller to be the team's current manager, or to be ADMIN.
         */
        put: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: components["parameters"]["TeamId"];
                };
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["TeamRequest"];
                };
            };
            responses: {
                /** @description Updated */
                204: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                /** @description Validation error */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                /** @description Missing or invalid token */
                401: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                /** @description Caller is not the team's manager and not ADMIN */
                403: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ApiError"];
                    };
                };
                /** @description Not found */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        post?: never;
        /**
         * Delete a team
         * @description Requires the caller to be the team's current manager, or to be ADMIN.
         */
        delete: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: components["parameters"]["TeamId"];
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Deleted */
                204: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                /** @description Missing or invalid token */
                401: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                /** @description Caller is not the team's manager and not ADMIN */
                403: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ApiError"];
                    };
                };
                /** @description Not found */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/teams/{id}/members/{userId}": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: components["parameters"]["TeamId"];
                userId: components["parameters"]["UserIdInPath"];
            };
            cookie?: never;
        };
        get?: never;
        /**
         * Add a member to the team (idempotent)
         * @description Requires the caller to be the team's current manager, or to be ADMIN.
         */
        put: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: components["parameters"]["TeamId"];
                    userId: components["parameters"]["UserIdInPath"];
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Member added (or already present) */
                204: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                /** @description Validation error (e.g. adding the manager as a member) */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                /** @description Missing or invalid token */
                401: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                /** @description Caller is not the team's manager and not ADMIN */
                403: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ApiError"];
                    };
                };
                /** @description Team not found */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        post?: never;
        /**
         * Remove a member from the team
         * @description Requires the caller to be the team's current manager, or to be ADMIN.
         */
        delete: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: components["parameters"]["TeamId"];
                    userId: components["parameters"]["UserIdInPath"];
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Removed */
                204: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                /** @description Cannot remove the last member or the manager via this endpoint */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                /** @description Missing or invalid token */
                401: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                /** @description Caller is not the team's manager and not ADMIN */
                403: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ApiError"];
                    };
                };
                /** @description Team not found */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/feedbacks": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List feedbacks for the caller
         * @description Lists feedback records scoped by `view`. Scoping is always relative to the caller,
         *     including ADMIN callers.
         *
         *     - `view=received` (the default): rows where the caller is the subject AND `visibility`
         *       is `PROVIDER_SUBJECT`, `PROVIDER_REQUESTER_SUBJECT` or `PUBLIC` — i.e. the rows the
         *       subject is allowed to read. `PROVIDER_REQUESTER` rows never appear in this view.
         *     - `view=provided`: rows where the caller is the provider, regardless of visibility
         *       (a provider may always read their own records).
         *     - `view=team`: rows where the subject is a member of a team the caller manages
         *       (the caller's subordinates), unrestricted by visibility or status. Intended for a
         *       manager's overview of their team's feedback. A caller who manages no team gets an
         *       empty page.
         *
         *     Supports offset pagination, sorting and filtering.
         *
         *     - Sortable fields: `id`, `requesterName`, `subjectName`, `providerName`, `visibility`,
         *       `status`, `lastModified`. Default sort is `id` ascending. `id` ascending is always
         *       appended as a deterministic tiebreaker.
         *     - Filters (all optional, all whitelisted):
         *       - `requesterName` — case-insensitive substring match against the requester's name.
         *         Rows without a requester never match when this filter is set.
         *       - `subjectName` — case-insensitive substring match against the subject's name.
         *       - `providerName` — case-insensitive substring match against the provider's name.
         *       - `providerId` — exact match against the provider's user id. Combined with
         *         `view=received`, this scopes the list to feedbacks a specific person gave the caller.
         *       - `subjectId` — exact match against the subject's user id. Combined with
         *         `view=provided`, this scopes the list to feedbacks the caller gave a specific person.
         *       - `visibility` — exact match against the visibility enum.
         *       - `status` — exact match against the status enum.
         *       - `lastModified[gte]` — lower bound (inclusive) on `lastModified`, epoch
         *         milliseconds. Returns rows changed at or after this instant.
         *     - `content` is returned as `contentPreview`, capped at 200 characters; it is neither
         *       sortable nor filterable.
         *
         *     Malformed query parameters (unknown view, unknown sort field, unknown enum value,
         *     out-of-range page/pageSize) respond with `400` and an `ApiError` body.
         */
        get: {
            parameters: {
                query?: {
                    /** @description 1-based page index. Defaults to 1. */
                    page?: components["parameters"]["Page"];
                    /** @description Rows per page. Defaults to 20, maximum 100. */
                    pageSize?: components["parameters"]["PageSize"];
                    /**
                     * @description Sort spec. Format: `field` (ascending) or `-field` (descending). Multiple fields are
                     *     comma-separated, leftmost wins: `sort=-createdAt,id`. The endpoint declares its
                     *     sortable-field whitelist; unknown fields are rejected with `400`. `id` ascending is
                     *     always appended as a deterministic tiebreaker.
                     */
                    sort?: components["parameters"]["Sort"];
                    /** @description Which caller-relative slice of feedbacks to list. */
                    view?: "received" | "provided" | "team";
                    /** @description Case-insensitive substring match against the requester's name. */
                    requesterName?: string;
                    /** @description Case-insensitive substring match against the subject's name. */
                    subjectName?: string;
                    /** @description Case-insensitive substring match against the provider's name. */
                    providerName?: string;
                    /** @description Exact match against the provider's user id. */
                    providerId?: number;
                    /** @description Exact match against the subject's user id. */
                    subjectId?: number;
                    /** @description Exact match against the record's visibility. */
                    visibility?: "PROVIDER_SUBJECT" | "PROVIDER_REQUESTER" | "PROVIDER_REQUESTER_SUBJECT" | "PUBLIC";
                    /** @description Exact match against the record's status. */
                    status?: "REQUESTED" | "DRAFT" | "SENT" | "WITHDRAWN" | "REJECTED";
                    /** @description Lower bound (inclusive) on `lastModified`, epoch milliseconds. Returns rows changed at or after this instant. */
                    "lastModified[gte]"?: number;
                };
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description A page of feedbacks */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["FeedbackPage"];
                    };
                };
                /** @description Malformed query parameters */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ApiError"];
                    };
                };
                /** @description Missing or invalid token */
                401: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ApiError"];
                    };
                };
            };
        };
        put?: never;
        /**
         * Create a feedback record
         * @description Any authenticated user may create a feedback record.
         */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["FeedbackRequest"];
                };
            };
            responses: {
                /** @description Created */
                201: {
                    headers: {
                        Location?: string;
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["FeedbackResponse"];
                    };
                };
                /** @description Validation error or referenced user does not exist */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                /** @description Missing or invalid token */
                401: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/feedbacks/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: components["parameters"]["FeedbackId"];
            };
            cookie?: never;
        };
        /**
         * Fetch a feedback record
         * @description Authorization is derived from the record's `visibility` and the caller's
         *     relationship to the row:
         *     - `PROVIDER_SUBJECT`:           provider or subject may read.
         *     - `PROVIDER_REQUESTER`:         provider or requester may read.
         *     - `PROVIDER_REQUESTER_SUBJECT`: provider, requester or subject may read.
         *     - `PUBLIC`:                     any authenticated user may read.
         *     ADMIN may read any record.
         */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: components["parameters"]["FeedbackId"];
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["FeedbackResponse"];
                    };
                };
                /** @description Missing or invalid token */
                401: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                /** @description Caller's relationship to the row does not satisfy `visibility` */
                403: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ApiError"];
                    };
                };
                /** @description Not found */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        /**
         * Replace a feedback record
         * @description Only the record's provider (or ADMIN) may modify a feedback.
         */
        put: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: components["parameters"]["FeedbackId"];
                };
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["FeedbackRequest"];
                };
            };
            responses: {
                /** @description Updated */
                204: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                /** @description Validation error or invalid status transition */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                /** @description Missing or invalid token */
                401: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                /** @description Caller is not the feedback's provider and not ADMIN */
                403: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ApiError"];
                    };
                };
                /** @description Not found */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        post?: never;
        /**
         * Delete a feedback record
         * @description Only the record's provider (or ADMIN) may delete a feedback.
         */
        delete: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: components["parameters"]["FeedbackId"];
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Deleted */
                204: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                /** @description Missing or invalid token */
                401: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                /** @description Caller is not the feedback's provider and not ADMIN */
                403: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ApiError"];
                    };
                };
            };
        };
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/templates": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List templates
         * @description Lists templates. Any authenticated user may read.
         *
         *     Supports offset pagination, sorting and filtering.
         *
         *     - Sortable fields: `id`, `name`. Default sort is `id` ascending. `id` ascending is
         *       always appended as a deterministic tiebreaker.
         *     - Filter (optional, whitelisted):
         *       - `name` — case-insensitive substring match against the template name.
         *     - `content` is returned as `contentPreview`, capped at 200 characters; it is neither
         *       sortable nor filterable.
         *
         *     Malformed query parameters (unknown sort field, out-of-range page/pageSize) respond
         *     with `400` and an `ApiError` body.
         */
        get: {
            parameters: {
                query?: {
                    /** @description 1-based page index. Defaults to 1. */
                    page?: components["parameters"]["Page"];
                    /** @description Rows per page. Defaults to 20, maximum 100. */
                    pageSize?: components["parameters"]["PageSize"];
                    /**
                     * @description Sort spec. Format: `field` (ascending) or `-field` (descending). Multiple fields are
                     *     comma-separated, leftmost wins: `sort=-createdAt,id`. The endpoint declares its
                     *     sortable-field whitelist; unknown fields are rejected with `400`. `id` ascending is
                     *     always appended as a deterministic tiebreaker.
                     */
                    sort?: components["parameters"]["Sort"];
                    /** @description Case-insensitive substring match against the template name. */
                    name?: string;
                };
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description A page of templates */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["TemplatePage"];
                    };
                };
                /** @description Malformed query parameters */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ApiError"];
                    };
                };
                /** @description Missing or invalid token */
                401: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ApiError"];
                    };
                };
            };
        };
        put?: never;
        /**
         * Create a template
         * @description ADMIN only.
         */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["TemplateRequest"];
                };
            };
            responses: {
                /** @description Created */
                201: {
                    headers: {
                        Location?: string;
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["TemplateResponse"];
                    };
                };
                /** @description Validation error (e.g. blank name) */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                /** @description Missing or invalid token */
                401: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                /** @description Caller is not ADMIN */
                403: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ApiError"];
                    };
                };
                /** @description A template with the same name already exists */
                409: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ApiError"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/templates/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: components["parameters"]["TemplateId"];
            };
            cookie?: never;
        };
        /**
         * Fetch a template
         * @description Any authenticated user may read.
         */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: components["parameters"]["TemplateId"];
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["TemplateResponse"];
                    };
                };
                /** @description Missing or invalid token */
                401: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                /** @description Not found */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        /**
         * Replace a template
         * @description ADMIN only.
         */
        put: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: components["parameters"]["TemplateId"];
                };
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["TemplateRequest"];
                };
            };
            responses: {
                /** @description Updated */
                204: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                /** @description Validation error (e.g. blank name) */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                /** @description Missing or invalid token */
                401: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                /** @description Caller is not ADMIN */
                403: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ApiError"];
                    };
                };
                /** @description Not found */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                /** @description A template with the same name already exists */
                409: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ApiError"];
                    };
                };
            };
        };
        post?: never;
        /**
         * Delete a template
         * @description ADMIN only.
         */
        delete: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: components["parameters"]["TemplateId"];
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Deleted */
                204: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                /** @description Missing or invalid token */
                401: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                /** @description Caller is not ADMIN */
                403: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ApiError"];
                    };
                };
            };
        };
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/notifications": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List the caller's notifications
         * @description Lists notifications addressed to the calling user (`recipientId` = caller). The list is
         *     always scoped to the caller, including for ADMIN — there is no cross-user view.
         *
         *     Notifications are generated as a side-effect of other activities; there is no create
         *     endpoint.
         *
         *     Supports offset pagination, sorting and filtering.
         *
         *     - Sortable fields: `id`, `timestamp`. Default sort is `timestamp` descending (newest
         *       first). `id` ascending is always appended as a deterministic tiebreaker.
         *     - Filter (optional, whitelisted):
         *       - `wasSeen` — `true`/`false`; restricts to seen / unseen notifications.
         *
         *     Malformed query parameters (unknown sort field, out-of-range page/pageSize, non-boolean
         *     `wasSeen`) respond with `400` and an `ApiError` body.
         */
        get: {
            parameters: {
                query?: {
                    /** @description 1-based page index. Defaults to 1. */
                    page?: components["parameters"]["Page"];
                    /** @description Rows per page. Defaults to 20, maximum 100. */
                    pageSize?: components["parameters"]["PageSize"];
                    /**
                     * @description Sort spec. Format: `field` (ascending) or `-field` (descending). Multiple fields are
                     *     comma-separated, leftmost wins: `sort=-createdAt,id`. The endpoint declares its
                     *     sortable-field whitelist; unknown fields are rejected with `400`. `id` ascending is
                     *     always appended as a deterministic tiebreaker.
                     */
                    sort?: components["parameters"]["Sort"];
                    /** @description Restrict to seen (`true`) or unseen (`false`) notifications. */
                    wasSeen?: boolean;
                };
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description A page of notifications */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["NotificationPage"];
                    };
                };
                /** @description Malformed query parameters */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ApiError"];
                    };
                };
                /** @description Missing or invalid token */
                401: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ApiError"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/notifications/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: components["parameters"]["NotificationId"];
            };
            cookie?: never;
        };
        /**
         * Fetch a notification
         * @description The recipient or an ADMIN may read.
         */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: components["parameters"]["NotificationId"];
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["NotificationResponse"];
                    };
                };
                /** @description Missing or invalid token */
                401: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                /** @description Caller is neither the recipient nor ADMIN */
                403: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ApiError"];
                    };
                };
                /** @description Not found */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        put?: never;
        post?: never;
        /**
         * Delete a notification
         * @description The recipient or an ADMIN may delete.
         */
        delete: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: components["parameters"]["NotificationId"];
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Deleted */
                204: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                /** @description Missing or invalid token */
                401: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                /** @description Caller is neither the recipient nor ADMIN */
                403: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ApiError"];
                    };
                };
                /** @description Not found */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/notifications/{id}/seen": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: components["parameters"]["NotificationId"];
            };
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Mark a notification as seen
         * @description Sets `wasSeen` to `true`. Idempotent. The recipient or an ADMIN may call it.
         */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: components["parameters"]["NotificationId"];
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Marked as seen */
                204: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                /** @description Missing or invalid token */
                401: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                /** @description Caller is neither the recipient nor ADMIN */
                403: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ApiError"];
                    };
                };
                /** @description Not found */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        LoginRequest: {
            /** Format: email */
            email: string;
            password: string;
        };
        LoginResponse: {
            token: string;
            /**
             * Format: int64
             * @description Token expiry as Unix epoch milliseconds
             */
            expiresAt: number;
            /** Format: int64 */
            userId: number;
            /**
             * @description Global role of the authenticated user.
             * @enum {string}
             */
            role: "ADMIN" | "USER";
        };
        UserRequest: {
            name: string;
            /** Format: email */
            email: string;
            password: string;
            /**
             * @description Honoured only when the caller is ADMIN. Non-ADMIN callers must omit this
             *     field or send the value the user already has, otherwise the request is
             *     rejected with 403. Omitted on create defaults to USER.
             * @enum {string}
             */
            role?: "ADMIN" | "USER";
        };
        UserUpdateRequest: {
            name: string;
            /** Format: email */
            email: string;
            /**
             * @description Honoured only when the caller is ADMIN. Non-ADMIN callers must omit this
             *     field or send the value the user already has, otherwise the request is
             *     rejected with 403. Omitting it keeps the user's current role.
             * @enum {string}
             */
            role?: "ADMIN" | "USER";
        };
        PasswordUpdateRequest: {
            password: string;
        };
        UserResponse: {
            /** Format: int64 */
            id: number;
            name: string;
            /** Format: email */
            email: string;
            /**
             * @description Global role.
             * @enum {string}
             */
            role: "ADMIN" | "USER";
        };
        UserPage: {
            items: components["schemas"]["UserResponse"][];
            page: number;
            pageSize: number;
            /**
             * Format: int64
             * @description Row count after filters, before pagination.
             */
            total: number;
        };
        TeamRequest: {
            name: string;
            /** Format: int64 */
            managerId: number;
            /**
             * @description Defaults to an empty list when omitted. Zero-member teams are allowed;
             *     members can be added later via the `/api/teams/{id}/members/{userId}` sub-resource.
             */
            memberIds?: number[];
        };
        TeamResponse: {
            /** Format: int64 */
            id: number;
            name: string;
            /** Format: int64 */
            managerId: number;
            memberIds: number[];
        };
        TeamListItem: {
            /** Format: int64 */
            id: number;
            name: string;
            /** Format: int64 */
            managerId: number;
            managerName: string;
            /** @description True when the user referenced by `managerId` has been soft-deleted. */
            managerDeleted: boolean;
        };
        TeamPage: {
            items: components["schemas"]["TeamListItem"][];
            page: number;
            pageSize: number;
            /**
             * Format: int64
             * @description Row count after filters, before pagination.
             */
            total: number;
        };
        TeamMemberListItem: {
            /** Format: int64 */
            userId: number;
            name: string;
            email: string;
            /** Format: int64 */
            teamId: number;
            teamName: string;
        };
        TeamMemberPage: {
            items: components["schemas"]["TeamMemberListItem"][];
            page: number;
            pageSize: number;
            /**
             * Format: int64
             * @description Row count after filters, before pagination.
             */
            total: number;
        };
        FeedbackRequest: {
            /** Format: int64 */
            requesterId?: number | null;
            /** Format: int64 */
            subjectId: number;
            /** Format: int64 */
            providerId: number;
            /** @enum {string} */
            visibility: "PROVIDER_SUBJECT" | "PROVIDER_REQUESTER" | "PROVIDER_REQUESTER_SUBJECT" | "PUBLIC";
            /** @enum {string} */
            status: "REQUESTED" | "DRAFT" | "SENT" | "WITHDRAWN" | "REJECTED";
            /** @default  */
            content: string;
        };
        FeedbackResponse: {
            /** Format: int64 */
            id: number;
            /** Format: int64 */
            requesterId?: number | null;
            /** Format: int64 */
            subjectId: number;
            /** Format: int64 */
            providerId: number;
            /** @enum {string} */
            visibility: "PROVIDER_SUBJECT" | "PROVIDER_REQUESTER" | "PROVIDER_REQUESTER_SUBJECT" | "PUBLIC";
            /** @enum {string} */
            status: "REQUESTED" | "DRAFT" | "SENT" | "WITHDRAWN" | "REJECTED";
            content: string;
            /**
             * Format: int64
             * @description Epoch milliseconds of the last change. Server-managed and read-only.
             */
            lastModified: number;
        };
        FeedbackListItem: {
            /** Format: int64 */
            id: number;
            /** Format: int64 */
            requesterId?: number | null;
            /** @description Null when the record has no requester. */
            requesterName?: string | null;
            /** @description True when the user referenced by `requesterId` has been soft-deleted. False when there is no requester. */
            requesterDeleted: boolean;
            /** Format: int64 */
            subjectId: number;
            subjectName: string;
            /** @description True when the user referenced by `subjectId` has been soft-deleted. */
            subjectDeleted: boolean;
            /** Format: int64 */
            providerId: number;
            providerName: string;
            /** @description True when the user referenced by `providerId` has been soft-deleted. */
            providerDeleted: boolean;
            /** @enum {string} */
            visibility: "PROVIDER_SUBJECT" | "PROVIDER_REQUESTER" | "PROVIDER_REQUESTER_SUBJECT" | "PUBLIC";
            /** @enum {string} */
            status: "REQUESTED" | "DRAFT" | "SENT" | "WITHDRAWN" | "REJECTED";
            /** @description First 200 characters of `content`. */
            contentPreview: string;
            /**
             * Format: int64
             * @description Epoch milliseconds of the last change. Server-managed and read-only.
             */
            lastModified: number;
        };
        FeedbackPage: {
            items: components["schemas"]["FeedbackListItem"][];
            page: number;
            pageSize: number;
            /**
             * Format: int64
             * @description Row count after filters, before pagination.
             */
            total: number;
        };
        TemplateRequest: {
            name: string;
            /** @default  */
            content: string;
        };
        TemplateResponse: {
            /** Format: int64 */
            id: number;
            name: string;
            content: string;
        };
        TemplateListItem: {
            /** Format: int64 */
            id: number;
            name: string;
            /** @description First 200 characters of `content`. */
            contentPreview: string;
        };
        TemplatePage: {
            items: components["schemas"]["TemplateListItem"][];
            page: number;
            pageSize: number;
            /**
             * Format: int64
             * @description Row count after filters, before pagination.
             */
            total: number;
        };
        NotificationResponse: {
            /** Format: int64 */
            id: number;
            /** Format: int64 */
            recipientId: number;
            /**
             * Format: int64
             * @description Epoch milliseconds when the notification was generated. Server-managed.
             */
            timestamp: number;
            message: string;
            /** @description Optional in-app path to open from the notification; absent when there is nowhere to go. */
            link?: string | null;
            /** @description Whether the recipient has marked the notification as seen. */
            wasSeen: boolean;
        };
        NotificationPage: {
            items: components["schemas"]["NotificationResponse"][];
            page: number;
            pageSize: number;
            /**
             * Format: int64
             * @description Row count after filters, before pagination.
             */
            total: number;
        };
        ApiError: {
            /** @example conflict */
            error: string;
            message: string;
        };
    };
    responses: never;
    parameters: {
        UserId: number;
        UserIdInPath: number;
        TeamId: number;
        FeedbackId: number;
        TemplateId: number;
        NotificationId: number;
        /** @description 1-based page index. Defaults to 1. */
        Page: number;
        /** @description Rows per page. Defaults to 20, maximum 100. */
        PageSize: number;
        /**
         * @description Sort spec. Format: `field` (ascending) or `-field` (descending). Multiple fields are
         *     comma-separated, leftmost wins: `sort=-createdAt,id`. The endpoint declares its
         *     sortable-field whitelist; unknown fields are rejected with `400`. `id` ascending is
         *     always appended as a deterministic tiebreaker.
         */
        Sort: string;
    };
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export type operations = Record<string, never>;
