-- Seeds the default feedback templates (bilingual EN/PL section scaffolds) so a freshly
-- built database has ready-to-use templates in the admin Templates screen. Idempotent:
-- `name` is UNIQUE, so re-runs or partial pre-existing sets are safe.

INSERT INTO templates (name, content) VALUES
    ('Start / Stop / Continue', '### Start / Zacznij ...
...

### Stop / Przestań ...
...

### Continue / Kontynuuj ...
...
'),
    ('Situation / Behavior / Impact / Request', '### Situation / Zdarzenie
...

### Behavior / Zachowanie
...

### Impact / Rezultat
...

### Request / Sugestia
...'),
    ('Continue / Adjust / Try', '### Continue / Bez zmian
...

### Adjust / Zmodyfikuj
...

### Try / Spróbuj nowego
...'),
    ('Observation / Effect / Alternative', '### Observation / Obserwacja
...

### Effect / Rezultat
...

### Alternative / Sugestia
...')
ON CONFLICT (name) DO NOTHING;
