ktor:
  development: true
  deployment:
    port: 8080
  application:
    modules:
      - ch.nokillswit.HttpKt.configureHttp
      - ch.nokillswit.MonitoringKt.configureMonitoring
      - ch.nokillswit.SerializationKt.configureSerialization
      - ch.nokillswit.SecurityKt.configureSecurity
      - ch.nokillswit.WebsocketsKt.configureWebsockets
      - ch.nokillswit.DIKt.configureDependencyInjection
      - ch.nokillswit.ServerOpenTelemetryKt.configureOpenTelemetry
      - ch.nokillswit.AutoHeadResponseKt.configureAutoHeadResponse
      - ch.nokillswit.FlywayKt.configureFlyway
      - ch.nokillswit.ExposedKt.configureExposed
      - ch.nokillswit.AuthKt.configureAuth
      - ch.nokillswit.ResourcesKt.configureResources
      - ch.nokillswit.RequestValidationKt.configureRequestValidation
      - ch.nokillswit.RoutingKt.configureRouting

jwt:
  secret: "$JWT_SECRET:secret"
  issuer: "$JWT_ISSUER:http://0.0.0.0:8080/"
  audience: "$JWT_AUDIENCE:lettuce-api"
  realm: "$JWT_REALM:lettuce-api"
  expiresInSeconds: "$JWT_EXPIRES_IN_SECONDS:3600"

postgres:
  jdbcUrl: "$POSTGRES_JDBC_URL:jdbc:postgresql://localhost:5432/lettuce"
  r2dbcUrl: "$POSTGRES_R2DBC_URL:r2dbc:postgresql://localhost:5432/lettuce"
  user: "$POSTGRES_USER:lettuce"
  password: "$POSTGRES_PASSWORD:lettuce"
